#!/usr/bin/env sh

# Short helper script to generate self signed SSL certificates.

openssl req -new -newkey rsa:4096 -days 365000 -nodes -x509 \
        -keyout /config/frontend/nginx/certs/ssl.key  -out /config/frontend/nginx/certs/ssl.crt
