#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
    /config{/php,/rtorrent/rtorrent_sess} \
    /data{/complete,/downloading,/rtwatch} \
    /run/php \
    /logs{/rtorrent,/rutorrent}


[[ ! -d /var/www/public/rutorrent ]] && (git clone https://github.com/Novik/ruTorrent.git /var/www/public/rutorrent  && chown -R swerp:swerp /var/www/public/rutorrent)

[[ ! -e /config/rtorrent/rtorrent.rc ]] && \
    cp /defaults/rtorrent.rc /config/rtorrent/rtorrent.rc

if [ ! -e "/config/php/php.ini" ]; then
    cp /etc/php7/php.ini /config/php/php.ini
    sed -i -e 's/\(register_argc_argv .*=\).*/\1 On/g' /config/php/php.ini
fi

cp /config/php/php.ini /etc/php7/php.ini
rm -rf /var/www/public/rutorrent/conf/config.php && cp /defaults/rutorrent-conf/config.php /var/www/public/rutorrent/conf/config.php
# delete lock file if exists
[[ -e /config/rtorrent/rtorrent_sess/rtorrent.lock ]] && \
    rm /config/rtorrent/rtorrent_sess/rtorrent.lock

# permissions
chown swerp:swerp \
    /data \
    /data{/complete,/downloading,/rtwatch}

chown -R swerp:swerp \
    /config \
    /run \
    /logs

