#!/usr/bin/with-contenv bash

# create .autodl config dir and link
[[ ! -d /config/autodl ]] && \
  (mkdir /config/autodl && \
    chown -R swerp:swerp /config/autodl)

[[ ! -d /home/swerp ]] && (mkdir /home/swerp && chown -R swerp:swerp /home/swerp)

# get rutorrent plugin
[[ ! -d /web/rutorrent/plugins/autodl-rutorrent/.git ]] && \
(git clone https://github.com/autodl-community/autodl-rutorrent.git /web/rutorrent/plugins/autodl-irssi && \
chown -R swerp:swerp /web/rutorrent/plugins/autodl-irssi/)

# get autodl script for irssi
[[ ! -d /config/irssi/scripts/.git ]] && (mkdir -p /config/irssi/scripts && \
  git clone https://github.com/autodl-community/autodl-irssi.git /config/irssi/scripts && \
  mkdir /config/irssi/scripts/autorun && \
  ln -s /config/irssi/scripts/autodl-irssi.pl /config/irssi/scripts/autorun/autodl-irssi.pl && \
  chown -R swerp:swerp /config/irssi )

# get updated trackers for irssi-autodl
wget --quiet -O /tmp/trackers.zip https://github.com/autodl-community/autodl-trackers/archive/master.zip && \
cd /config/.irssi/scripts/AutodlIrssi/trackers && \
unzip -q -o -j /tmp/trackers.zip && \
rm /tmp/trackers.zip

# update rutorrent plugin
cd /web/rutorrent/plugins/autodl-irssi/ || exit
git pull
chown -R swerp:swerp /web/rutorrent/plugins/autodl-irssi

# make sure perl is in irssi startup
echo "load perl" > /config/irssi/startup

# symlink autodl/irssi folders to root
ln -s /config/autodl /root/.autodl
ln -s /config/irssi /root/.irssi
chown -R swerp:swerp /root/.autodl
chown -R swerp:swerp /root/.irssi

# update autodl script for irssi
cd /config/irssi/scripts || exit
git pull
chown -R swerp:swerp /config/irssi
