#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config/tmp /detach_sess

[[ ! -L /home/swerp/.autodl ]] && ln -s /config/.autodl /home/swerp/.autodl

[[ ! -L /config/.irssi/scripts/autorun/autodl-irssi.pl ]] && \
  ln -s /config/.irssi/scripts/autodl-irssi.pl /config/.irssi/scripts/autorun/autodl-irssi.pl

[[ ! -f /config/.autodl/autodl.cfg ]] && cp /defaults/autodl.cfg /config/.autodl/autodl.cfg

[[ ! -f /config/.autodl/autodl2.cfg ]] && cp /defaults/autodl2.cfg /config/.autodl/autodl2.cfg

[[ ! -f /var/www/public/rutorrent/plugins/autodl-irssi/conf.php ]] && \
  cp /defaults/conf.php /var/www/public/rutorrent/plugins/autodl-irssi/conf.php

# set perms
chown swerp:swerp -R /config /detach_sess
chown swerp:swerp -R /var/www/public/rutorrent
chown swerp:swerp /data
