#!/usr/bin/with-contenv bash
umask 002

if [ -f "/detach_sess/.rtorrent" ]; then
  rm -f /detach_sess/.rtorrent || true
sleep 1s
fi

dtach -n /detach_sess/.rtorrent \
s6-setuidgid swerp /usr/bin/rtorrent \
-n -o import=/config/rtorrent/rtorrent.rc

until [ -e "/config/rtorrent/session/rtorrent.lock" ];
do
sleep 1s
done

rtorrent_pid=$(cat /config/rtorrent/session/rtorrent.lock | cut -d '+' -f 2)
tail -n 1 -f /config/log/rtorrent/rtorrent.log "$rtorrent_pid"
