#!/usr/bin/with-contenv bash
export HOME=/config

function ts {
  echo [`date '+%b %d %X'`]
}
function copyfiles {
  if [ ! -e "/config/filebot.conf" ]; then
  	cp /app/filebot.conf /config/filebot.conf
  	echo "Config not found, copying it now..."
  else
    echo "Config found. Skipping setup..."
  fi
  if [ ! -e "/config/filebot.sh" ]; then
    cp /app/filebot.sh /config/filebot.sh
    echo "Filebot not found, copying it now..."
  else
    echo "Filebot found. Skipping setup..."
  fi
}

function setup_opensubtitles_account {
  . /config/filebot.conf

  if [ "$OPENSUBTITLES_USER" != "" ]; then
    echo "$(ts) Configuring for OpenSubtitles user \"$OPENSUBTITLES_USER\""
    echo -en "$OPENSUBTITLES_USER\n$OPENSUBTITLES_PASSWORD\n" | exec s6-setuidgid swerp filebot -script fn:configure
  else
    echo "$(ts) No OpenSubtitles user set. Skipping setup..."
  fi
}
copyfiles
setup_opensubtitles_account

chown -R swerp:swerp /app /config
